### ISSUE TITLE
The problem about train

### ISSUE THREAD

**Issue by huzijun1996** [trikpachu/A3GC-IP#2]
I have noticed that there are usually multiple models, criteria, and schedules in the training code. Do you want readers to try them out on their own? Which one did you use in your paper?

**Comment by trikpachu** [comment]
They are all used in the paper. The train/test scripts with ending aagc and agc concern only the ablations, tp is short for transpose, and the rest should be clear. With respect to hyperparameters, refer to the readme or the paper. The values indicated in the readme are the ones used in the paper.

**Comment by huzijun1996** [comment]
Sorry, maybe I didn't express myself clearly before. Is the purpose of setting different input_size and rotsize in train_a3gc_tp.py for ablation experiments? I don't quite understand.
model1=PoseNet3 (input_size=12, rotsize=3, adjacency=nira, n_hidden=args. hu1, device=device). to (device)
model2=PoseNet3 (input_size=15, rotsize=3, adjacency=nira, n_hidden=args. hu2, device=device). to (device)
model3=PoseNet3 (input_size=15, rotsize=9, adjacency=nira, n_hidden=args. hu3, device=device). to (device)
Meanwhile,  it has been stated in net_aagc.py that input_size=12 and rotsize=9
def _ init__ (self, input_size=12, rotsize=9, adjacency=None, device=torch. device ("CPU"), n_hidden=256):
Super()__ Init__ ()
Which one should be used for model1, model2, and model3 in actual training?
It is not possible to train directly according to the Python train_a3gc_tp.py in readme because there are errors in the code. The error message is in line 231,232,290, requiring the version of the model and criterion (line 290 should be a typo). This kind of problem also exists in train_aggc_tp.py, train_agc_tp.py, train_ggru_tp.py, train_tp.py.

**Comment by trikpachu** [comment]
Please also post the error message when referring to one. Input_size and rotsize are simply input and output dimensions. They are different, since the model1 takes your actual data as input, and outputs what goes into model2 and so forth, until model3 returns the actual output (rotation matrices). ~The only thing going wrong on your end, which I can imagine, is something being wrong with the data. Did you use the preprocessing scripts and data loader from the code? Otherwise I might only be able to help you, if I really know whats going on at all.~

**Comment by trikpachu** [comment]
I checked the lines you mentioned, line 290 was a typo, sorry for that. I should've checked the code again after making it more readable :.D
Regarding the lines 231 and 232 I need to check that later. I actually implemented the .half just in case when writing everything up, but never used it, so I don't know if it works as intended.

**Comment by trikpachu** [comment]
Nevermind, the .half stuff simply didn't work because I never changed it from the beginning of writing my code, when I had only one instead of three models. I'll adapt it soon. Feel free to ask again if there is more, but please also provide the error message then. I don't care if the text around the error message is chinese (I guessed from your name), the traceback should still be readable and helpful.

**Comment by trikpachu** [comment]
I fixed the Issues and the training scripts should run without problems now when not using --half. Unfortunately, using half precision raises errors for which I do not have the time to fix now, so it simply won't work as is. I hope you have enough VRAM, so this won't become a problem (it should run fine on at least a 1080 without half precision). I don't think it will be of help for you at this point, but I also added a Dockerfile to get the dependencies right. 

Thanks for pointing out the errors, and feel free to come back if I missed more :)
